set global local_infile=1;
use stats;

load data local infile "../core/AllstarFull.csv" IGNORE  into table allstarfull columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/Appearances.csv" IGNORE  into table appearances columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/AwardsManagers.csv" IGNORE  into table awardsmanagers columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/AwardsPlayers.csv" IGNORE  into table awardsplayers columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/AwardsShareManagers.csv" IGNORE  into table awardssharemanagers columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/AwardsSharePlayers.csv" IGNORE  into table awardsshareplayers columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/Batting.csv" IGNORE  into table batting columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/BattingPost.csv" IGNORE  into table battingpost columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/CollegePlaying.csv" IGNORE  into table collegeplaying columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/Fielding.csv" IGNORE  into table fielding columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/FieldingOF.csv" IGNORE  into table fieldingof columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/FieldingOFSplit.csv" IGNORE  into table fieldingofsplit columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/FieldingPost.csv" IGNORE  into table fieldingpost columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/HallOfFame.csv" IGNORE  into table halloffame columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/HomeGames.csv" IGNORE  into table homegames columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/Managers.csv" IGNORE  into table managers columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/ManagersHalf.csv" IGNORE  into table managershalf columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/Parks.csv" IGNORE  into table parks columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/People.csv" IGNORE  into table people columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/Pitching.csv" IGNORE  into table pitching columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/PitchingPost.csv" IGNORE  into table pitchingpost columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/Salaries.csv" IGNORE  into table salaries columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/Schools.csv" IGNORE  into table schools columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/SeriesPost.csv" IGNORE  into table seriespost columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/Teams.csv" IGNORE  into table teams columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/TeamsFranchises.csv" IGNORE  into table teamsfranchises columns terminated by ',' lines terminated by '\n' ignore 1 lines;
load data local infile "../core/TeamsHalf.csv" IGNORE  into table teamshalf columns terminated by ',' lines terminated by '\n' ignore 1 lines;

set global local_infile=0;
